@startuml
actor "Customer Manager" as User
participant ListJobOpeningApplicationsUI as UI
participant ListJobOpeningApplicationsController as CTRL
database JobApplicationRepository as ApplicationRepository

title US 1005 - Listing applications for a job opening\nPartial - Setup

activate User
activate UI

alt if there are job openings that belong to the current Customer Manager

UI --> User : lists their job openings

User -> UI : selects the job opening

UI -> CTRL: findJobApplicationsByJobOpening(jobOpening)
activate CTRL

CTRL -> ApplicationRepository** : create instance

CTRL -> ApplicationRepository : findJobApplicationsByJobOpening(jobOpening)
activate ApplicationRepository

ApplicationRepository --> CTRL : List<JobApplication>
deactivate ApplicationRepository

CTRL --> UI : List<JobApplication>
deactivate CTRL

alt if there are job applications for that job opening

UI --> User : lists the job applications

end alt

end alt

deactivate UI

@enduml