@startuml
actor "Customer Manager" as User
participant SetupJobOpeningRecuitmentPhasesUI as UI
participant SetupJobOpeningRecuitmentPhasesController as CTRL
participant Jobs4uUserAuthService as Service
database JobOpeningRepository as Repository
participant JobOpening as Object

title US 1007 - Setting up Recruitment Phases

activate User

User -> UI : requests to setup the recruitment phases for a job opening

activate UI

UI -> CTRL** : create

UI -> CTRL : findCustomerManagerJobOpeningsNoRecruitmentProcess()
activate CTRL

CTRL -> Service** : create instance

CTRL -> Service : authenticatedUser().getEmail().toString()
activate Service
Service --> CTRL : current customer manager email (String)
deactivate Service

CTRL -> Repository** : create instance

CTRL -> Repository : findJobOpeningsOfCustomerManagerNoRecruitmentProcess(email)
activate Repository

Repository -> Object**
Repository -> Object : get list of
activate Object
deactivate Object

Repository --> CTRL : List<JobOpening>
deactivate Repository

CTRL --> UI : List<JobOpening>
deactivate CTRL

alt if there are job openings that meet that requirement

UI --> User : lists their job openings that don't have their recruitment phases set up

User -> UI : selects the job opening

loop if inserted close date is before start date

UI --> User : asks for start and close date for the Application phase

User -> UI : provides start and end date

end loop

UI -> CTRL : insertApplicationPhase(phase)
activate CTRL
deactivate CTRL

loop if inserted close date is before start date

UI --> User : asks for start and close date for the Screening phase

User -> UI : provides start and end date

end loop

UI -> CTRL : insertScreeningPhase(phase)
activate CTRL
deactivate CTRL

UI --> User : asks if job opening will have Interviews phase

User -> UI : answers y/n

alt if job opening has Interviews phase

loop if inserted close date is before start date

UI --> User : asks for start and close date for the Interviews phase

User -> UI : provides start and end date

end loop

UI -> CTRL : insertInterviewsPhase(phase)
activate CTRL
deactivate CTRL

end alt

loop if inserted close date is before start date

UI --> User : asks for start and close date for the Analysis phase

User -> UI : provides start and end date

end loop

User -> CTRL : insertAnalysisPhase(phase)
activate CTRL
deactivate CTRL

loop if inserted close date is before start date

UI --> User : asks for start and close date for the Result phase

User -> UI : provides start and end date

end loop

UI -> CTRL : insertResultPhase(phase)
activate CTRL
deactivate CTRL

UI -> CTRL : updateJobOpening(jobOpening)
activate CTRL

CTRL -> Object : defineRecruitmentProcess(phases)
activate Object
deactivate Object

CTRL -> Repository : save(jobOpening)
activate Repository
deactivate Repository
CTRL --> UI
deactivate CTRL

UI --> User : informs user of operation success

end alt

deactivate UI

@enduml