@startuml
actor "Customer Manager" as User
participant System as SYS


title US 1017 - Uploading Interview Answers


activate User

User -> SYS : requests to upload a text file with the\n candidate responses for an interview

activate SYS

group do while(!verificationSuccessful)

SYS --> User : asks to select a job opening

User -> SYS : selects a job opening

note right

loops until a valid job opening is chosen

end note

end

group do while(!verificationSuccessful)

SYS --> User : asks to select a job application

User -> SYS : selects application

note right

loops until a valid job application is chosen

end note

end

SYS --> User : asks to select a file for uploading

User -> SYS : selects a file

SYS --> User : uploads the text file

deactivate SYS

@enduml